# Generated by Django 4.2.8 on 2023-12-24 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="galaxy", name="universe_name",),
        migrations.AddField(
            model_name="galaxy",
            name="universe_name_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="universe.universe",
            ),
        ),
    ]
