# Generated by Django 4.2.8 on 2023-12-24 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0002_remove_galaxy_universe_name_galaxy_universe_name_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="planet", name="solar_system",),
        migrations.RemoveField(model_name="solarsystem", name="galaxy_name",),
        migrations.AddField(
            model_name="planet",
            name="solar_system_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="universe.solarsystem",
            ),
        ),
        migrations.AddField(
            model_name="solarsystem",
            name="galaxy_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="universe.galaxy",
            ),
        ),
    ]
