# Generated by Django 4.0.3 on 2023-12-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blackhole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackhole',
            name='item_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
