# Generated by Django 4.0.3 on 2023-12-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
